### ISSUE TITLE
Conditions for termination of forward tracking iterations are too tight

### ISSUE THREAD

**Issue by tongtongcao** [JeffersonLab/clas12-offline-software#1043]
Since the conditions are too tight and all conditions need to be satisfied simultaneously, KF process reaches maximum of iterations almost  for all seeds constructed by cross combination.
We should reset conditions so that cooking efficiency is improved, while tracking results are affected slightly.
[Discussion about termination of iterations for forward tracking.pdf](https://github.com/JeffersonLab/clas12-offline-software/files/10760570/Discussion.about.termination.of.iterations.for.forward.tracking.pdf)

**Comment by raffaelladevita** [comment]
Addressed by #1044
