### ISSUE TITLE
flag double-hits in CND reconstruction via the hit status variable

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-offline-software#1045]
Charged tracks can cross both paddles in a CND sector because of the curvature in the solenoid field. When that happens, the pulses measured by the left and right PMT have the same time and the z of the reconstructed hit is wrong. Because of this track-to-hit matching can fail.  Since there is not clean way to correct these hits at the CND reconstruction level, these will be flagged via the status variable in CND::hits, which will then be propagated to the CND::clusters and then to REC::scintillator.

**Comment by baltzell** [comment]
I think this was addressed by #1059?

**Comment by raffaelladevita** [comment]
that's correct
