### ISSUE TITLE
Are all the banks the RICH group wants really in the DST schema?

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#1090]

**Comment by baltzell** [comment]
Doesn't look like it.  They ought to be here:  https://github.com/JeffersonLab/clas12-offline-software/blob/c57b4c1c5458d00b85561607dcf7599738a30999/etc/bankdefs/util/bankSplit.py#L64

**Comment by raffaelladevita** [comment]
The list above is consistent with what presented by the RICH group at the March 2nd software meeting. See https://clasweb.jlab.org/wiki/images/2/2b/2023-03-02_RICH_pass2.pdf

For the record, in RG-B Spring19 production data, these banks amount to 17% of the total DST size. RICH::tdc alone amounts to 12.5% of the total DST size.

**Comment by baltzell** [comment]
That's quite a bit given the state ...
