### ISSUE TITLE
Delete stale branches before running BFG cleanup

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#1111]

**Comment by baltzell** [comment]
**From David:**
ClosestApproach

**From Veronique:**
iss774-detachedVtx
iss827-CVTTrackEff
iss827-CVTTrackEff-DevM
iss827-CVTTrackEff-DevM2
iss827-CVTTrackEff-DevM3
iss827-CVTTrackEff-DevM4

**Comment by zieglerv** [comment]
Raffaella says cvtGeoCompare, dev-align3 and dev-align-merge should NOT go….

On Apr 26, 2023, at 4:05 PM, Nathan Baltzell ***@***.******@***.***>> wrote:



From David:
ClosestApproach

From Veronique:
cvtGeoCompare
dev-align3
dev-align-merge
dev-align3
dev-align-merge
iss774-detachedVtx
iss827-CVTTrackEff
iss827-CVTTrackEff-DevM
iss827-CVTTrackEff-DevM2
iss827-CVTTrackEff-DevM3
iss827-CVTTrackEff-DevM4
iss827-CVTTrackEff-DevM4

**Comment by baltzell** [comment]
Already updated in the first comment above.
