### ISSUE TITLE
Fix mismatched trkID in cluster bank

### ISSUE THREAD

**Issue by zieglerv** [JeffersonLab/clas12-offline-software#1121]

**Comment by zieglerv** [comment]
The track id in REC::Track does not match the ID in the CVTRec::Tracks bank

**Comment by baltzell** [comment]
> The track id in REC::Track does not match the ID in the CVTRec::Tracks bank

Is this correct?

**Comment by zieglerv** [comment]
Index in REC::Track matches the row the the track is stored in.

On May 9, 2023, at 4:33 AM, Nathan Baltzell ***@***.******@***.***>> wrote:



The track id in REC::Track does not match the ID in the CVTRec::Tracks bank

Is this correct?

**Comment by zieglerv** [comment]
Index in REC::Track matches the row in CVTRec::Tracks.  The misunderstanding was thinking that index was the same as track ID in the CVT bank.  f Now that we remember correctly the meaning of index in REC::Track, this is a non-issue, which can be closed.
