### ISSUE TITLE
Logging verbosity

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#1127]
Some runs are giving a lot of this, filling up disk quotas and causing other jobs to crash:

Missing DC::jitter entry for crate/slot = 0/0
Missing DC::jitter entry for crate/slot = 0/0
Missing TT entry for slco = 1 2 70 10
Missing TT entry for slco = 1 7 101 10
Missing DC::jitter entry for crate/slot = 0/0
Missing TT entry for slco = 1 7 102 10
Missing TT entry for slco = 1 22 80 10
Missing DC::jitter entry for crate/slot = 0/0
Missing DC::jitter entry for crate/slot = 0/0

**Comment by zieglerv** [comment]
This comes from the method getDCRBJitter(int sector, int layer, int wire, int order) in HitReader in DC reconstruction,
where the indexed table IndexedTable(2, "jitter:I”) and/or reverse translation table have no entry.
Could this be an issue with the decoding?

On May 12, 2023, at 9:05 AM, Nathan Baltzell ***@***.******@***.***>> wrote:


Some runs are giving a lot of this, filling up disk quotas and causing other jobs to crash:

Missing DC::jitter entry for crate/slot = 0/0
Missing DC::jitter entry for crate/slot = 0/0
Missing TT entry for slco = 1 2 70 10
Missing TT entry for slco = 1 7 101 10
Missing DC::jitter entry for crate/slot = 0/0
Missing TT entry for slco = 1 7 102 10
Missing TT entry for slco = 1 22 80 10
Missing DC::jitter entry for crate/slot = 0/0
Missing DC::jitter entry for crate/slot = 0/0

**Comment by baltzell** [comment]
Maybe it's all about the denoise marking order, the "10s".

**Comment by raffaelladevita** [comment]
Yes, the DCRB jitter correction uses the translation table and requires the true order . It should be fixed in 9.0.0Il giorno 12 mag 2023, alle ore 10:17 AM, Nathan Baltzell ***@***.***> ha scritto:﻿
Maybe it's all about the denoise marking order, the "10s".

**Comment by baltzell** [comment]
Yes, the culprit logs were ~10 days ago with an older software version.
