### ISSUE TITLE
database variations

### ISSUE THREAD

**Issue by drewkenjo** [JeffersonLab/clas12-offline-software#149]
I was adding capability to change geometry database variation to the DC reconstruction code, and noticed that while variation for geometry database was hardcoded to ConstantProvider, the variation for calibration database was sometimes hardcoded directly to DataBaseConstantProvider but mostly was hardcoded through method "setVariation" of ConstantsManager.
Now, to change geometry database variation I added method to CLASResources class (the one that returns CLAS12DIR variable) and used it to read GEOMETRYDATABASEVARIATION environment variable. So the person who runs the reconstruction should set this variable to their geometry database variation, or it will be "default".
Shortly, we have two variations for geometry database and calibration database. Don't know if it's a issue or not, but be aware of that.

**Comment by baltzell** [comment]
Looks like this issue will be resolved/affected by Raffaella's proposal for maintaining CCDB rungroup geometry variations.  See branch rungroupGeometry .  Reopen/adjust if not.
