### ISSUE TITLE
Trajectory Detector Descriptors

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#174]
TimeBasedTrkg::Trajectory.did and CVTRec::Trajectory.LayerTrackIntersPlane need an enum class to store their numbering conventions.   Similar to org.jlab.detector.base.DetectorType.

Also, add CND layers and CTOF to CVTRec::Trajectory

**Comment by fbossu** [comment]
We can create two enum classes, one for forward and one for the central. 
Where is the best place to put these enums? I guess at the same location of DetectorType

**Comment by baltzell** [comment]
Sounds like people prefer DetectorType plus a new DetectorLayer for this (which includes bank format change).
