### ISSUE TITLE
Remove dependence on javafx

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#276]

**Comment by drewkenjo** [comment]
JCSG package is based on existing package: "Java implementation of BSP based CSG (Constructive Solid Geometry)". And it depends on javafx. I don't think it would be easy to remove the dependency from jcsg.

**Comment by baltzell** [comment]
Primary issue was with openjdk in previous years, but as of 11 openjdk supports FX, and our Travis builds have been using that for a while, so it seems this is not a big deal anymore.
