### ISSUE TITLE
Finalize CVT x/y vertex convention

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#292]
Potentially needs fixing in at least EventBuilder, pending input from Francesco/Maxime.

**Comment by fbossu** [comment]
Correct sign convention included in CVTAlignment-swim branch

**Comment by baltzell** [comment]
It's here (where d0/phi0 is CVTRec::Tracks.d0/phi0):
 
https://github.com/JeffersonLab/clas12-offline-software/blob/d6d2c729c7612efa2e662adff3f7164a2f0f1364/common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorData.java#L567-L568

**Comment by zieglerv** [comment]
With the current code helix parameterization the definition should be:
 vx = -d0*Math.sin(phi0); 
 vy = d0*Math.cos(phi0);

**Comment by baltzell** [comment]
PR #448
