### ISSUE TITLE
Throttle memory usage on decoder/evio2hipo

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#401]
Currently decoder uses 3 GB (physical, 6 GB virtual) on the JLab batch farm.  Is that really necessary, or can the current "-Xmx1536m -Xms1024m" be stricter?

**Comment by gavalian** [comment]
After some tests I discovered that you can run decoder with -Xmx512m -Xms256m setting.
In this case the memory usage hovers around 700-710 MB, so setting 1GB limit should be fine.
However, lowering memory to -Xmx256 causes garbage collector to work harder and the decoding
slows down to half speed. So we can change decoder script to have maximum memory set to 512MB.

**Comment by baltzell** [comment]
Might as well do the same for evio2hipo?

**Comment by baltzell** [comment]
Done for evio2hipo, however the decoder effectively has some type of memory leak.
