### ISSUE TITLE
Drop clusterID of hits in the FTCAL::hits bank, that point to underthreshold clusters.

### ISSUE THREAD

**Issue by rafopar** [JeffersonLab/clas12-offline-software#571]
In the  FTCAL::hits bank, the clusterID is pointing to the index of the cluster to which it belongs to.
However because of a threshold, not all clusters are written out into the FTCAL::clusters bank.
As a result hits from underthreshold clusters are pointing to clusters that don't exist in FTCAL::clusters bank.

**Comment by raffaelladevita** [comment]
#673
