### ISSUE TITLE
Fix service error reporting and job abortion

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#572]
* If a non-existing CCDB variation is specified, retries occur on every event, i.e. the mechanism that reports to Clara to abort on failed database connections isn't sensitive to non-existing variation
* Non-Clara usage does not abort in any case but should (decoder, evio2hipo, recon-util)

**Comment by raffaelladevita** [comment]
- if non existent field map is specified, magfield gives exception at every event but Clara does not abort

**Comment by baltzell** [comment]
Note the error catching in ReconstructionEngine:  https://github.com/JeffersonLab/clas12-offline-software/blob/development/common-tools/clas-reco/src/main/java/org/jlab/clas/reco/ReconstructionEngine.java#L256-L364
