### ISSUE TITLE
Preserve mapping between hit-based and time-based tracks

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#617]
Probably starting with the existing `id` variable in the two track banks that are output from tracking services.  Currently they are just independent counters.  For DSTs, there may be an added linking bank.

**Comment by zieglerv** [comment]
Implementation ready to be tested in branch /iss-617-DC-HB2TBPreserve

**Comment by baltzell** [comment]
PR #623
