### ISSUE TITLE
Address dedx=0 for CTOF

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#704]
Occaisonally dedx==0 while energy!=0 in DST banks.  One hypothesis is different track-hit/cluster matching criteria in upstream detector services and the event builder.

**Comment by baltzell** [comment]
This should be already addressed?

**Comment by baltzell** [comment]
This should already addressed, ultimately by #1009

**Comment by raffaelladevita** [comment]
Addressed by #1010
