### ISSUE TITLE
disable CND-CTOF veto in EB per request of CND expert

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-offline-software#766]

**Comment by baltzell** [comment]
What does it mean?  They want to just pull the complicated veto and do beta-only differentiation for photon/neutron?

**Comment by raffaelladevita** [comment]
Yes, they want just the beta cut and they plan to refine the pid in the analysis. They also think the veto is partially wrong and that’s why they want to remove it now

**Comment by baltzell** [comment]
Sad

**Comment by baltzell** [comment]
Addressed by #768
