### ISSUE TITLE
JAXB implementation missing

### ISSUE THREAD

**Issue by gavalian** [JeffersonLab/clas12-offline-software#800]
When switching to JDK 11, there was an issue with JAXB implementation.
Problems with parsing XML files, for EVIO and BOS libraries in clas-io 
common tools.

The fix is described here. and will be implemented.
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception

**Comment by baltzell** [comment]
I think this was resolved by #802 ?
