### ISSUE TITLE
EC Last-a-Foam thickness should be 76 mm

### ISSUE THREAD

**Issue by forcar** [JeffersonLab/clas12-offline-software#840]
Original specifications for EC had Last-a-Foam thickness=76 mm, which is consistent with design drawings and external measurements of the EC lid thickness.   

Releases of GEMC prior to 2.4  used 76.2 mm, which is still in geometry.pl:  https://github.com/gemc/detectors/blob/master/clas12/ec/geometry.pl

Current tagged versions show 25.4 mm for the G4Trap half-width: https://github.com/gemc/clas12Tags/blob/master/4.3.0/experiments/clas12/ec/ec__geometry_java.txt

**Comment by baltzell** [comment]
What will it take to make this happen?

**Comment by raffaelladevita** [comment]
It’s on my todo list: we have all information but need some time for testing

**Comment by baltzell** [comment]
Do we need this for pass2?

**Comment by raffaelladevita** [comment]
Cole should confirm but I believe it affects only the simulation geometry. So it is not relevant for pass2 but should still be fixed

**Comment by forcar** [comment]
It is intended to make simulations of e- and gamma sampling fractions more realistic. Recall photon SF correction is derived from MC.
