### ISSUE TITLE
DataSourceProcessorPane doesn't allow setting the verbosity of the underlying DataSourceProcessor

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-offline-software#899]
All applications using the DataSourceProcessorPane, like mon12 or the calibration suites, do not report exceptions in the event processing because these are caught at https://github.com/JeffersonLab/clas12-offline-software/blob/fe68c2bc773aec704837ee6c7f7d301eae2ebd0f/common-tools/clas-io/src/main/java/org/jlab/io/task/DataSourceProcessor.java#L135-L139
This makes identifying problems difficult. 
A method to set the verbosity of the DataSourceProcessor should be added to the DataSourceProcessorPane

**Comment by baltzell** [comment]
I guess maybe there was a good reason not to just print all exceptions?  Otherwise we probably just want to change verboseMode to true by default.

**Comment by baltzell** [comment]
Is this still relevant?

**Comment by raffaelladevita** [comment]
Yes, it is. It’s a small change that should be done to facilitate debugging calibration code

**Comment by baltzell** [comment]
Maybe you just want this in the catch:
System.out.println(e.getMessage());

**Comment by baltzell** [comment]
closed by #1087
