### ISSUE TITLE
Add information on seeding type in CVT track status word

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-offline-software#992]
The CVT track bank status word encodes information on the number of SVT and BMT clusters associated to the track and the number of KF iterations performed in fitting, see https://github.com/JeffersonLab/clas12-offline-software/blob/development/etc/bankdefs/hipo4/cvt.json#L407

The proposal is to use another digit to save the information on the track seed type: 1 - CA, 2 SVT-only, 3 new track finding

**Comment by baltzell** [comment]
Seems this won't be happening.

**Comment by raffaelladevita** [comment]
It's done in the new CVT branch at https://github.com/JeffersonLab/clas12-offline-software/commit/66e3e656d3eac043323aa074a3011e89971210f8
